name: Show GitHub Context

on: push

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch
        run: echo "Branch: ${{ github.ref }}"

      - name: Print actor
        run: echo "Triggered by: ${{ github.actor }}"
