name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd "$GITHUB_WORKSPACE"
          npm install

      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE"
          npm test

      - name: Work space
        run: echo "$GITHUB_WORKSPACE"

      - name: Run lint
        run: |
          cd "$GITHUB_WORKSPACE"
          npm run lint
